export const copyByLanguage = {
  en: {
    loanTypeTitle: 'Select Loan Type',
    autoLoans: 'Auto Loans',
    autoRefinance: 'Auto Refinance',
    cosignerTitle: 'Are You Applying With A Co-Signer?',
    byMyself: 'By Myself',
    withCosigner: 'With Co-Signer',
    cosignerRelativeTitle: 'Is Your Co-Signer A Relative?',
    relative: 'Relative',
    nonRelative: 'Not Relative',
    sameAddressTitle: 'Does Your Co-Signer Live At The Same Address?',
    livesSameAddress: 'Lives At Same Address',
    notSameAddress: "Doesn't Live At Same Address",
    employmentTitle: 'Select Employment Type',
    fullTime: 'Full Time',
    partTime: 'Part Time',
    tempSeasonal: 'Temp/Seasonal',
    selfEmployed: 'Self Employed',
    ssiRetired: 'SSI / Retired',
    military: 'Military',
    disability: 'Disability',
    proofIncomeTitle: 'Select Proof Of Income Type',
    paystub: 'Paystub',
    w2: 'W2',
    taxes: 'Taxes',
    taxes2Years: 'Taxes 2 Years',
    form1099: '1099',
    proofBenefits: 'Proof Of Benefits',
    rewardLetter: 'Reward Letter',
    monthlyIncomeTitle: 'Select Monthly Income',
    other: 'Other',
    notProvided: 'Not provided',
    monthlyAmountLabel: 'Monthly',
    timeAtJobTitle: 'Choose Time At Job',
    over2Years: 'Over 2 Years',
    oneToTwoYears: '1-2 Years',
    lessThanYear: 'Less Than A Year',
    monthsLabel: 'Months',
    driversLicenseTitle: "Do You Have A Current Driver's License?",
    yes: 'Yes',
    no: 'No',
    downPaymentTitle: 'Select Down Payment Amount',
    downPaymentLabel: 'Down',
    enterDownPayment: 'Enter down payment amount',
    ssnItinTitle: 'Do You Have A Social Security Number or An ITIN Number?',
    socialSecurity: 'Social Security',
    itin: 'ITIN',
    dtiTitle: "Let's Calculate Your Debt To Income Ratio",
    dtiDescription:
      'Your debt-to-income ratio (DTI) is all your monthly debt payments divided by your gross monthly income. Recurring monthly debt can include things such as: car payments, credit cards, mortgage, personal loans, school loans, etc.',
    dtiCalculatorTitle: 'Debt To Income Ratio Calculator',
    recurringDebtLabel: 'Your Recurring Monthly Debt:',
    grossIncomeLabel: 'Your Gross Monthly Income:',
    skip: 'Skip',
    continue: 'Continue',
    repoTitle: 'Have You Ever Had A Repo?',
    residenceTimeTitle: 'Your Time At Current Residence?',
    over1Year: 'Over 1 Year',
    under1Year: 'Under 1 Year',
    zipTitle: 'Your Zip Code For Current Residence?',
    zipPlaceholder: 'Enter your zip code',
    approvalTitle: "What's the difference between approval and pre-approval?",
    approvalText:
      'One word: verification. Pre-approvals are an estimate, not a promise. A pre-approval is a non-binding statement saying, based on a cursory review of your unverified financial status, that you are eligible for a loan up to a certain amount. It is based on a credit check and (again unverified) claims of income and debt. The approval is a the process of obtaining a specific loan on a specific car for a specific amount. These are subject to review of a complete loan application.',
    exit: 'Exit',
    contactTitle: 'Provide Your Contact Information',
    firstNamePlaceholder: 'First Name',
    lastNamePlaceholder: 'Last Name',
    emailPlaceholder: 'Email Address',
    addressPlaceholder: 'Home Address',
    cityPlaceholder: 'City',
    statePlaceholder: 'State',
    zipPlaceholderForm: 'Zip Code',
    phonePlaceholder: 'Phone Number',
    jobTitleLabel: "What's Your Job Title",
    jobTitlePlaceholder: "What's your job title?",
    preApprovalAnswersTitle: 'Your Pre-Approval Answers',
    reviewTitle: 'Review & Continue',
    seeMonthlyPayment: 'Find Bank',
    summaryDebt: 'Debt',
    summaryIncome: 'Income',
    selectMonths: 'Select months',
    enterMonthlyIncome: 'Enter monthly income',
    fullNameLabel: 'Full Name',
    back: 'Back',
    uploadDocumentsTitle: 'Upload Required Documents',
    uploadDocumentsDescription: 'Please upload a photo of your driver\'s license and your most recent paycheck to complete your application.',
    driversLicenseLabel: 'Driver\'s License Photo',
    paycheckLabel: 'Paycheck / Pay Stub',
    submitDocuments: 'Submit Documents',
    uploadSuccess: 'Documents uploaded successfully!',
    uploadError: 'Failed to upload documents. Please try again.',
    selectFile: 'Select File',
    noFileSelected: 'No file selected',
  },
  es: {
    loanTypeTitle: 'Seleccione Tipo De Prestamo',
    autoLoans: 'Prestamo De Auto',
    autoRefinance: 'Refinanciamiento De Auto',
    cosignerTitle: 'Estas Solicitando Con Un Cosignatario?',
    byMyself: 'Por Mi Mismo',
    withCosigner: 'Con Cosignatario',
    cosignerRelativeTitle: 'Tu Cosignatario Es Un Familiar?',
    relative: 'Familiar',
    nonRelative: 'No Familiar',
    sameAddressTitle: 'Tu Cosignatario Vive En La Misma Direccion?',
    livesSameAddress: 'Vive En La Misma Direccion',
    notSameAddress: 'No Vive En La Misma Direccion',
    employmentTitle: 'Seleccione Tipo De Empleo',
    fullTime: 'Tiempo Completo',
    partTime: 'Medio Tiempo',
    tempSeasonal: 'Temporal/Estacional',
    selfEmployed: 'Autoempleado',
    ssiRetired: 'SSI / Jubilado',
    military: 'Militar',
    disability: 'Discapacidad',
    proofIncomeTitle: 'Seleccione Tipo De Comprobante De Ingresos',
    paystub: 'Talones De Pago',
    w2: 'W2',
    taxes: 'Impuestos',
    taxes2Years: 'Impuestos 2 Anos',
    form1099: '1099',
    proofBenefits: 'Prueba De Beneficios',
    rewardLetter: 'Carta De Beneficios',
    monthlyIncomeTitle: 'Seleccione Ingreso Mensual',
    other: 'Otro',
    notProvided: 'No provisto',
    monthlyAmountLabel: 'Mensual',
    timeAtJobTitle: 'Elija Tiempo En El Trabajo',
    over2Years: 'Mas De 2 Anos',
    oneToTwoYears: '1-2 Anos',
    lessThanYear: 'Menos De Un Ano',
    monthsLabel: 'Meses',
    driversLicenseTitle: 'Tiene Una Licencia De Conducir Vigente?',
    yes: 'Si',
    no: 'No',
    downPaymentTitle: 'Seleccione Monto Del Pago Inicial',
    downPaymentLabel: 'Pago Inicial',
    enterDownPayment: 'Ingrese el pago inicial',
    ssnItinTitle: 'Tiene Un Numero De Seguro Social O Un Numero ITIN?',
    socialSecurity: 'Seguro Social',
    itin: 'ITIN',
    dtiTitle: 'Calculemos Su Relacion Deuda/Ingreso',
    dtiDescription:
      'Su relacion deuda/ingreso (DTI) es el total de sus pagos mensuales de deuda dividido entre su ingreso mensual bruto. La deuda mensual recurrente puede incluir pagos de auto, tarjetas de credito, hipoteca, prestamos personales, prestamos estudiantiles, etc.',
    dtiCalculatorTitle: 'Calculadora De Relacion Deuda/Ingreso',
    recurringDebtLabel: 'Su Deuda Mensual Recurrente:',
    grossIncomeLabel: 'Su Ingreso Mensual Bruto:',
    skip: 'Omitir',
    continue: 'Continuar',
    repoTitle: 'Alguna Vez Tuvo Un Repo?',
    residenceTimeTitle: 'Tiempo En Su Residencia Actual?',
    over1Year: 'Mas De 1 Ano',
    under1Year: 'Menos De 1 Ano',
    zipTitle: 'Su Codigo Postal De Residencia Actual?',
    zipPlaceholder: 'Ingrese su codigo postal',
    approvalTitle: 'Cual Es La Diferencia Entre Aprobacion Y Preaprobacion?',
    approvalText:
      'Una palabra: verificacion. Las preaprobaciones son una estimacion, no una promesa. Una preaprobacion es una declaracion no vinculante que dice, basada en una revision superficial de su estado financiero no verificado, que usted es elegible para un prestamo hasta cierto monto. Se basa en una verificacion de credito y en afirmaciones (no verificadas) de ingresos y deudas. La aprobacion es el proceso de obtener un prestamo especifico para un auto especifico por un monto especifico. Estas estan sujetas a revision de una solicitud completa.',
    exit: 'Salir',
    contactTitle: 'Proporcione Su Informacion De Contacto',
    firstNamePlaceholder: 'Nombre',
    lastNamePlaceholder: 'Apellido',
    emailPlaceholder: 'Correo Electronico',
    addressPlaceholder: 'Direccion',
    cityPlaceholder: 'Ciudad',
    statePlaceholder: 'Estado',
    zipPlaceholderForm: 'Codigo Postal',
    phonePlaceholder: 'Numero De Telefono',
    jobTitleLabel: 'Cual Es Su Puesto De Trabajo',
    jobTitlePlaceholder: 'Cual es su puesto de trabajo?',
    preApprovalAnswersTitle: 'Sus Respuestas De Preaprobacion',
    reviewTitle: 'Revision Y Continuar',
    seeMonthlyPayment: 'Encontrar Banco',
    summaryDebt: 'Deuda',
    summaryIncome: 'Ingreso',
    selectMonths: 'Seleccione meses',
    enterMonthlyIncome: 'Ingrese ingreso mensual',
    fullNameLabel: 'Nombre Completo',
    back: 'Atras',
    uploadDocumentsTitle: 'Subir Documentos Requeridos',
    uploadDocumentsDescription: 'Por favor suba una foto de su licencia de conducir y su talon de pago mas reciente para completar su solicitud.',
    driversLicenseLabel: 'Foto de Licencia de Conducir',
    paycheckLabel: 'Talon de Pago',
    submitDocuments: 'Enviar Documentos',
    uploadSuccess: 'Documentos subidos exitosamente!',
    uploadError: 'Error al subir documentos. Por favor intente de nuevo.',
    selectFile: 'Seleccionar Archivo',
    noFileSelected: 'Ningun archivo seleccionado',
  },
}

export const getSteps = (language, copy) => {
  return [
    {
      id: 'loan-type',
      title: copy.loanTypeTitle,
      options: [
        { value: 'autoloan', icon: '🚗', label: copy.autoLoans },
        { value: 'autorefinance', icon: '🔄', label: copy.autoRefinance },
      ],
    },
    {
      id: 'cosigner',
      title: copy.cosignerTitle,
      question: copy.cosignerTitle,
      options: [
        { value: 'by-myself', icon: '👤', label: copy.byMyself },
        { value: 'with-cosigner', icon: '👥', label: copy.withCosigner },
      ],
    },
    {
      id: 'employment',
      title: copy.employmentTitle,
      options: [
        { value: 'fulltime', icon: '💼', label: copy.fullTime },
        { value: 'parttime', icon: '⏰', label: copy.partTime },
        { value: 'tempseasonal', icon: '🌿', label: copy.tempSeasonal },
        { value: 'selfemployed', icon: '🧾', label: copy.selfEmployed },
        { value: 'ssiretired', icon: '🏦', label: copy.ssiRetired },
        { value: 'military', icon: '🎖️', label: copy.military },
        { value: 'disability', icon: '♿', label: copy.disability },
      ],
    },
    {
      id: 'proof-of-income',
      title: copy.proofIncomeTitle,
      options: [
        { value: 'paystub', icon: '📄', label: copy.paystub },
        { value: 'w2', icon: '📋', label: copy.w2 },
        { value: 'taxes', icon: '📊', label: copy.taxes },
        { value: 'taxes-2-years', icon: '📅', label: copy.taxes2Years },
        { value: '1099', icon: '🔢', label: copy.form1099 },
        { value: 'proof-of-benefits', icon: '💊', label: copy.proofBenefits },
        { value: 'reward-letter', icon: '✉️', label: copy.rewardLetter },
      ],
    },
    {
      id: 'monthly-income',
      title: copy.monthlyIncomeTitle,
      options: [
        { value: '2000', icon: '💰', label: `$2,000 ${copy.monthlyAmountLabel}` },
        { value: '2500', icon: '💰', label: `$2,500 ${copy.monthlyAmountLabel}` },
        { value: '3000', icon: '💰', label: `$3,000 ${copy.monthlyAmountLabel}` },
        { value: '3500', icon: '💰', label: `$3,500 ${copy.monthlyAmountLabel}` },
        { value: '4000', icon: '💰', label: `$4,000 ${copy.monthlyAmountLabel}` },
        { value: '4500', icon: '💰', label: `$4,500 ${copy.monthlyAmountLabel}` },
        { value: '5000', icon: '💰', label: `$5,000 ${copy.monthlyAmountLabel}` },
        { value: 'other', icon: '✏️', label: copy.other },
      ],
    },
    {
      id: 'time-at-job',
      title: copy.timeAtJobTitle,
      options: [
        { value: 'over2years', icon: '⏳', label: copy.over2Years },
        { value: '1-2years', icon: '📆', label: copy.oneToTwoYears },
        { value: 'lessthanayear', icon: '🔰', label: copy.lessThanYear },
      ],
    },
    {
      id: 'drivers-license',
      title: copy.driversLicenseTitle,
      question: copy.driversLicenseTitle,
      options: [
        { value: 'yes', icon: '✅', label: copy.yes },
        { value: 'no', icon: '❌', label: copy.no },
      ],
    },
    {
      id: 'down-payment',
      title: copy.downPaymentTitle,
      options: [
        { value: '0down', icon: '💸', label: '$0' },
        { value: '1000-1500', icon: '💵', label: '$1,000-$1,500' },
        { value: '2000-2500', icon: '💵', label: '$2,000-$2,500' },
        { value: '3000-3500', icon: '💵', label: '$3,000-$3,500' },
        { value: '4000-4500', icon: '💵', label: '$4,000-$4,500' },
        { value: '5000-6500', icon: '💵', label: '$5,000-$6,500' },
        { value: 'other', icon: '✏️', label: copy.other },
      ],
    },
    {
      id: 'ssn-itin',
      title: copy.ssnItinTitle,
      question: copy.ssnItinTitle,
      options: [
        { value: 'social-security', icon: '🔒', label: copy.socialSecurity },
        { value: 'itin', icon: '🌍', label: copy.itin },
      ],
    },
    {
      id: 'repo-history',
      title: copy.repoTitle,
      question: copy.repoTitle,
      options: [
        { value: 'repo-yes', icon: '⚠️', label: copy.yes },
        { value: 'repo-no', icon: '✅', label: copy.no },
      ],
    },
    {
      id: 'zip-code',
      title: copy.zipTitle,
      question: copy.zipTitle,
      options: [],
    },
    {
      id: 'contact-info',
      title: copy.contactTitle,
      options: [],
    },
    {
      id: 'review',
      title: copy.reviewTitle,
      options: [],
    },
    {
      id: 'upload-documents',
      title: copy.uploadDocumentsTitle,
      options: [],
    },
  ]
}
